### ISSUE TITLE
 ViewRootImpl$CalledFromWrongThreadException : Only the original thread that created a view hierarchy can touch its views

### ISSUE THREAD

**Issue by MhtSuthar** [GitEliteNovice/CustomCamera#1]
Working fine but
When i click photo than this error comes,
line no 1262

**Comment by GitEliteNovice** [comment]
Can you tell , In which device are you testing the demo. I want to know, the problem occurring  in specific device, or in other devices also. Thanks

**Comment by santhosh-annam** [comment]
I see the same issue on Moto-G4 with Android7.0

**Comment by GitEliteNovice** [comment]
put all set ImageDrawable menthod inside run on ui thread like this...
getActivity().runOnUiThread(new Runnable() {
                @Override
                public void run() {
                    camera_flash.setImageDrawable(getContext().getResources().getDrawable(R.drawable.ic_flash_auto));                    
                }
            });


> I see the same issue on Moto-G4 with Android7.0

**Comment by GitEliteNovice** [comment]
i will update my code by the end of this week with bug fixes and add new features...
