### ISSUE TITLE
Cloning issue.

### ISSUE THREAD

**Issue by HassanUsman** [GitEliteNovice/CustomCamera#2]
Hi,
I'm facing this issue while cloning this project.

![image](https://user-images.githubusercontent.com/10232094/53856407-ac30e880-3ff3-11e9-9fcb-c2ef5ed2ca6d.png)

How I fix this issue.

**Comment by GitEliteNovice** [comment]
[Stackoverflow link for warning-templates-not-found](https://stackoverflow.com/questions/34877649/warning-templates-not-found-usr-local-git-share-git-core-templates)
try to use solutions mentioned in the  above link,and let me know if none of them doesn't work.

**Comment by HassanUsman** [comment]
I've downloaded the zip file and it's working fine now.
